name: Build and Unit Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.17.0"

      - name: Install dependencies
        run: npm run install:all

      - name: Install and build libraries
        run: npm run build:libs

      - name: Build AyoKoding
        run: npm run build:ayokoding

      - name: Run unit tests
        run: npm run test:unit
